#!/bin/sh

## live-tools(7) - System Support Scripts
## Copyright (C) 2013 Richard Nelson <unixabg@gmail.com>
##
## This program comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

# Defaults
_VERSION="7.4"

_URL="http://live.debian.net/files/stable/images/${_VERSION}/ARCH/webboot"

# Select the default live image config type.
_CONFIGTYPE="gnome-desktop"

#_ARCH - amd64 i386-486 i386-686
#_FLAVOUR - set from _ARCH selection and configured as 1 for 486 and 2 for 686
_ARCH="amd64"
_FLAVOUR=""

_NONFREE="No, do not include non-free."

_TARGET="/dev/sda"

# Persistence settings
_PERSISTENCE="No, do not make persistence."
_SIZE="250MB"

# Dependencies
if [ ! -e /sbin/parted ]
then
	echo "E: /sbin/parted - no such file"
	echo "E: On Debian based systems, parted can be installed with:"
	echo "E:   apt-get install parted"

	exit 1
fi

if [ ! -e /usr/bin/extlinux ]
then
	echo "E: /usr/bin/extlinux - no such file"
	echo "E: On Debian based systems, extlinux can be installed with:"
	echo "E:   apt-get install extlinux"

	exit 1
fi

if [ ! -e /usr/bin/wget ]
then
	echo "E: /usr/bin/wget - no such file"
	echo "E: On Debian based systems, wget can be installed with:"
	echo "E:   apt-get install wget"

	exit 1
fi

if [ ! -e /usr/share/syslinux/themes/debian/extlinux/splash.png ]
then
	echo "E: /usr/share/syslinux/themes/debian/extlinux/splash.png - no such file"
	echo "E: On Debian based systems, splash.png image can be installed with:"
	echo "E:   apt-get install syslinux-themes-debian"

	exit 1
fi

if [ ! -e /usr/lib/syslinux/vesamenu.c32 ]
then
	echo "E: /usr/lib/syslinux/vesamenu.c32 - no such file"
	echo "E: On Debian based systems, vesamenu.c32 can be installed with:"
	echo "E:   apt-get install syslinux-common"

	exit 1
fi

if [ ! -e /boot/memtest86+.bin ]
then
	echo "E: /boot/memtest86+.bin - no such file"
	echo "E: On Debian based systems, memtest86+ can be installed with:"
	echo "E:   apt-get install memtest86+"

	exit 1
fi

cat << EOF
######################################################
		live-medium-install
######################################################

######################################################
Please enter the image config type to download.
(default: ${_CONFIGTYPE})

 gnome-desktop
 kde-desktop
 lxde-desktop
 xfce-desktop
 standard
 rescue

EOF

# Ask for _CONFIGTYPE
echo -n ": "
read _READ

_CONFIGTYPE=${_READ:-${_CONFIGTYPE}}

cat << EOF

######################################################
Please enter the architecture you would like to install?
(default: ${_ARCH})

 amd64
 i386-486
 i386-686

EOF

# Ask for _ARCH
echo -n ": "
read _READ

_ARCH=${_READ:-${_ARCH}}

# Configure the _URL architecture and set _FLAVOUR on i386
case "${_ARCH}" in
	'amd64')
		_URL=$(echo ${_URL} | sed s@ARCH@amd64@)
		;;

	'i386-486')
		_URL=$(echo ${_URL} | sed s@ARCH@i386@)
		_FLAVOUR="1"
		;;

	'i386-686')
		_URL=$(echo ${_URL} | sed s@ARCH@i386@)
		_FLAVOUR="2"
		;;

	*)
		echo "Invalid architecture selection of ${_ARCH}, aborting."
		exit 1
		;;
esac

cat << EOF

######################################################
Do you want to use images which include the non-free
arvhive areas? Please enter 'Yes, include non-free.'
(default: ${_NONFREE})

EOF

# Ask for _NONFREE
echo -n ": "
read _READ

_NONFREE=${_READ:-${_NONFREE}}

# Configure _URL and _CONFIGTYPE to include non-free
case "${_NONFREE}" in
	'No, do not include non-free.')
		;;

	'Yes, include non-free.')
		_URL=$(echo ${_URL} | sed s@${_VERSION}@${_VERSION}+nonfree@)
		_CONFIGTYPE="${_CONFIGTYPE}+nonfree"
		;;

	*)
		echo "Invalid non-free selection of ${_NONFREE}, aborting."
		exit 1
		;;
esac

case "${_CONFIGTYPE}" in
	gnome-desktop|kde-desktop|lxde-desktop|xfce-desktop|standard|rescue|gnome-desktop+nonfree|kde-desktop+nonfree|lxde-desktop+nonfree|xfce-desktop+nonfree|standard+nonfree|rescue+nonfree)
		_FILES="debian-live-${_VERSION}-${_ARCH}-${_CONFIGTYPE}.vmlinuz${_FLAVOUR} debian-live-${_VERSION}-${_ARCH}-${_CONFIGTYPE}.initrd${_FLAVOUR}.img debian-live-${_VERSION}-${_ARCH}-${_CONFIGTYPE}.squashfs"
		;;

	*)
		echo "Invalid config type selection of ${_CONFIGTYPE}, aborting."
		exit 1
		;;
esac

cat << EOF

######################################################
Do you want to use persistence option?
Please enter: 'Yes, I want persistence.'
(default: ${_PERSISTENCE})

EOF

# Ask for _PERSISTENCE
echo -n ": "
read _READ

_PERSISTENCE=${_READ:-${_PERSISTENCE}}

case "${_PERSISTENCE}" in
	'Yes, I want persistence.')
		echo "What size? (default: ${_SIZE})"
		# Ask for _SIZE

		echo -n ": "
		read _READ
		_SIZE=${_READ:-${_SIZE}}

		;;

	'No, do not make persistence.')
		;;

	*)
		echo "Invalid persistance selection of ${_PERSISTANCE} , abort."
		exit 1
		;;
esac

# Display warning
cat << EOF
######################################################
WARNING: This will erase all data on the target device
######################################################

Please enter URL to download the ${_FILES} from
(default: ${_URL})
EOF

# Ask for URL
echo -n ": "
read _READ

_URL="${_READ:-${_URL}}"

# Display partitions
cat << EOF

-------------------------------------------------------------------------------
$(blkid | sort)
-------------------------------------------------------------------------------

EOF

# Ask for target device
echo -n "Please enter block device to install system to (default: ${_TARGET}): "
read _READ

_TARGET="${_READ:-${_TARGET}}"

if [ ! -b "${_TARGET}" ]
then
	echo "E: ${_TARGET} not a block device, aborting."
	exit 1
fi

cat << EOF

#########################################################
WARNING: This will erase all data on the ${_TARGET} device
#########################################################

You are about to do something potentially harmful.
To continue type in the phrase 'Yes, do as I say!'
EOF

echo -n ": "
read _CONTINUE

case "${_CONTINUE}" in
	'Yes, do as I say!')

		;;

	*)
		echo "Abort."

		exit 1
		;;
esac

# Zero fill just a bit
echo "Starting dd command for short zero fill..."
dd if=/dev/zero of=${_TARGET} bs=1024 count=1024

# Make a single partition
echo "Starting parted command to make label and partition..."
#parted -s -a optimal ${_TARGET} mklabel gpt -- mkpart primary ext4 1 -1
#parted -s -a optimal ${_TARGET} mklabel msdos -- mkpart primary ext4 1 3000
#parted -s -a optimal ${_TARGET} -- mkpart primary ext4 3000 -1
#parted -s -a optimal ${_TARGET} mklabel msdos -- mkpart primary ext4 1 -1
# Example of 10gb and swap.
#parted -s -a optimal ${_TARGET} mklabel msdos -- mkpart primary ext4 1 10000
#parted -s -a optimal ${_TARGET} -- mkpart primary linux-swap 10000 12000

if [ "${_PERSISTENCE}" = "Yes, I want persistence." ]
then
	echo "Creating install partition and reserving persistence space on drive."
	parted -s -a optimal ${_TARGET} mklabel msdos -- mkpart primary ext4 ${_SIZE}+1 -1

	echo "Now adding partition for persistence."
	parted -s -a optimal ${_TARGET} -- mkpart primary ext4 1 ${_SIZE}
	mkfs.ext4 -L persistence ${_TARGET}2
	mkdir /mnt2
	mount ${_TARGET}2 /mnt2
	echo "/ union" >> /mnt2/persistence.conf
	umount /mnt2
	rmdir /mnt2
else
	echo "Creating install partition on drive."
	parted -s -a optimal ${_TARGET} mklabel msdos -- mkpart primary ext4 1 -1
fi

# Set the block device to boot.
echo "Starting parted command to enable boot..."
parted -s ${_TARGET} --  set 1 boot on

# Make new filesystem on the new partitions.
echo "Making filesystem..."
mkfs.ext4 -L Firmware ${_TARGET}1
#mkfs.ext4 -L persistence ${_TARGET}2

# Mount the target filesystem
echo "Mounting file system to allow saving of webboot files..."
mount ${_TARGET}1 /mnt

# Create the directory to save webboot files
echo "Creating /live dir..."
mkdir -p /mnt/live

# Download the webboot files from server
echo "Downloading webboot files..."
for _FILE in ${_FILES}
do
	wget -c ${_URL}/${_FILE} -O /mnt/live/${_FILE}
done

# Renaming files
mv /mnt/live/debian-live-*.vmlinuz${_FLAVOUR} /mnt/live/vmlinuz
mv /mnt/live/debian-live-*.initrd${_FLAVOUR}.img /mnt/live/initrd.img
mv /mnt/live/debian-live-*.squashfs /mnt/live/filesystem.squashfs

# Writing mbr
# FIXME: needs update for syslinux 6.0
dd if=/usr/lib/extlinux/mbr.bin of="${_TARGET}" bs=440 count=1 conv=notrunc

# Configuring bootloader
mkdir -p /mnt/boot/extlinux

cp /usr/lib/syslinux/vesamenu.c32 /mnt/boot/extlinux/
cp /usr/share/syslinux/themes/debian/extlinux/splash.png /mnt/boot/extlinux/
cp /boot/memtest86+.bin /mnt/boot/

cat > /mnt/boot/extlinux/extlinux.conf << EOF
default live
prompt 0
timeout 50

default vesamenu.c32
menu background splash.png
menu title Debian Linux Firmware Version ${_VERSION}
menu separator
menu separator
menu separator
menu separator
menu separator
menu separator
menu separator
menu color title	* #FFFFFFFF *
menu color border	* #00000000 #00000000 none
menu color sel		* #ffffffff #76a1d0ff *
menu color hotsel	1;7;37;40 #ffffffff #76a1d0ff *
menu color tabmsg	* #ffffffff #00000000 *
menu color help		37;40 #ffdddd00 #00000000 none
menu vshift 9
menu rows 10
menu helpmsgrow 15
# The command line must be at least one line from the bottom.
menu cmdlinerow 16
menu timeoutrow 16
menu tabmsgrow 18
menu tabmsg Press ENTER to boot or TAB to edit a menu entry


label live
	menu label ^Live
	menu default
	linux /live/vmlinuz
	initrd /live/initrd.img
EOF

if [ "${_PERSISTENCE}" = "Yes, I want persistence." ]
then
    echo '\tappend boot=live config vga=normal video=vesa quiet splash persistence' >> /mnt/boot/extlinux/extlinux.conf
else
    echo '\tappend boot=live config vga=normal video=vesa quiet splash' >> /mnt/boot/extlinux/extlinux.conf
fi

cat >> /mnt/boot/extlinux/extlinux.conf << EOF

label live-failsafe
	menu label Live (failsafe)
	linux /live/vmlinuz
	initrd /live/initrd.img
	append boot=live config memtest noapic noapm nodma nomce nolapic nomodeset nosmp nosplash vga=normal

label memtest
	menu label Memory Diagnostic Tool (memtest86+)
	linux /boot/memtest86+.bin
EOF

# Writing bootloader
extlinux --install /mnt/boot/extlinux

# Sync and umount
echo "Cleanup with sync and umount..."
umount /mnt
sync

echo "Please halt your machine and boot up to your live firmware."
